version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student_feedback
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/student_feedback
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - db

  # Course Service
  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/student_feedback
    volumes:
      - ./course-service:/app
      - /app/node_modules
    depends_on:
      - db

  # Feedback Service
  feedback-service:
    build:
      context: ./feedback-service
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/student_feedback
    volumes:
      - ./feedback-service:/app
      - /app/node_modules
    depends_on:
      - db

  # Admin Service
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3004
      - NEXT_PUBLIC_AUTH_SERVICE_URL=http://auth-service:3001
      - NEXT_PUBLIC_COURSE_SERVICE_URL=http://course-service:3002
      - NEXT_PUBLIC_FEEDBACK_SERVICE_URL=http://feedback-service:3003
    volumes:
      - ./admin-service:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - course-service
      - feedback-service

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - course-service
      - feedback-service
      - admin-service

volumes:
  postgres_data: